# This workflow will build the extension against the latest Liquibase artifact
name: "Nightly build"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1-5'

jobs:
    nightly-build:
      uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@v0.5.5
      with:
        nightly: true
        java: '[11, 17, 18]'
      secrets: inherit