# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Test Extention

on: [ pull_request]

jobs:
  test:
    name: Java ${{ matrix.java }}, Cassandra ${{ matrix.cassandra }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Liquibase-Hub Repo
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - run: docker network create mycassandranetwork
      - run: docker run -p 9042:9042 --rm --name mycassandra --network mycassandranetwork -d cassandra
      - run: sleep 30
      - run: docker run --network mycassandranetwork --rm -v $(pwd):/tmp cassandra cqlsh -f /tmp/test.cql mycassandra