# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Test Extention

on: [ pull_request]

jobs:
  test:
    name: Java ${{ matrix.java }}, Cassandra ${{ matrix.cassandra }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 16]
        cassandra: [2.1, 2.2, 3.0, 3.11, 4.0]
    services:
      cassandra:
        image: cassandra:${{ matrix.cassandra }}
        # ports:
        #   - 9042:9042
    steps:
    - uses: actions/checkout@v2
    - name: Cache Local Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Init Cassandra Database
      run: cqlsh -f /tmp/test.cql cassandra
    - name: Test With Maven
      run: mvn -B test --file pom.xml
      
  build:
    needs: [test]
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Local Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build With Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: liquibase-cassandra
        path: target/*.jar
