name: Release Extension to Sonatype

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write
  actions: read # required by "Get build-logic ref" to query the Actions API (TECHOPS-609)

jobs:
  release:
    uses: liquibase/build-logic/.github/workflows/extension-release-published.yml@main
    secrets: inherit
